### PR TITLE
Autoswitch to DownloadPageLoader when chapter is downloaded

### LINKED ISSUE #1112: [Bug] New chapters not available if they appear while app is in reading mode
### Device information
* Tachiyomi version: 1.4.3
* Android phone & version: Motorola G5s Plus, 8.1

There are actually two bugs, but I believe they are of the same origin and nature, so I will refer to them in one topic.

Bug 1 - new chapters
## Steps to reproduce
1. Start reading last chapter (or any chapter, you just have to be at the very end to trigger bug)
2. Wait until new chapters for this title are released, stay in reading mode (can lock screen, switch apps, etc, as long as app is not unloaded from memory)
3. Try to scroll to new chapter

### Expected behavior
Newly available chapters is opened

### Actual behavior
New chapter is not opened, "this is the last chapter"

Bug 2 - loading chapters
## Steps to reproduce
1. Add few chapters into downloading queue
2. Start reading last loaded chapter so far, keep download in background
3. Stay in reading mode, wait until next chapter is downloaded
4. Scroll to next chapter

### Expected behavior
Next chapter is opened from cache

### Actual behavior
Next chapter is being loaded from server despite having it in cache.

This one is easy to verify if you disable network after next page is loaded successfully. If you try to scroll to next chapter, it will attempt to load it from server until it gives timeout error or until network is available again. But if you exit reading mode, you can open next chapter from list without any problem.

### PR DESCRIPTION
**Pull request by nzoba**
This PR contains:

- Autoswitch to `DownloadPageLoader` if reading from `HttpSource` when a chapter's download ends while being read (Closes #1112 only part 2)

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt [hunk 1]
```diff
@@ -210,6 +217,26 @@ abstract class PagerViewer(val activity: ReaderActivity) : BaseViewer {
         }
     }
 
+    /**
+     * Switch to DownloadPageLoader when the chapter is downloaded
+     */
+    private fun verifyIfShouldSwitchToDownloadLoader(currentReaderChapter: ReaderChapter) {
+        val loader = currentReaderChapter.pageLoader ?: return
+        if (loader is HttpPageLoader) {
+            val downloadManager = Injekt.get<DownloadManager>()
```
Comment (Jays2Kings) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt:226]: make the downloadManager in readerpresenter non-private and use it here, instead of constantly fetching it

**Review by Jays2Kings — COMMENTED** [review]
I'm not 100% on the logic, I might have to re-read it again sometime, but if it helps to reduce, I'd only have the logic switch from http to download loader only for chapters you're not on. If you're opening a chapter thats still downloading, thats on you

**Comment by nzoba** [comment]
This feature was thought to ease the 2 sides if a chapter's download finish while you are already reading it :
1. The pages will load faster for the user since it will use the downloaded pages instead of the preloading (even if he can just leave and reopen the reader)
2. More importantly, less requests to the source for the same reason (can't really force the user to quit the reader for that)

But it might be overkill for a really specific case 🤔

**Comment by Jays2Kings** [comment]
I think its a rare usecase, and Im suggesting only so you dont have to worry about the double page logic (which might still have to be there, if it does, I'd honestly just skip this pr and reject the initial issue)

But if it's possible to change the loader for the chapter you're not on and have simpler logic, then idc about those who start a download and opening the chapter thats downloading

**Comment by nzoba** [comment]
Sorry I forgot about this PR
As you said, it was far too complicated (and horrible code), especially since it was only to answer a really specific case (and avoid screen flickering on current chapter)
I simplified the logic as much as possible so now it's only a few lines associated to the preload of next/previous chapters
